export const albumActionTypes = {
    GET_ALBUMS_REQUEST: "GET_ALBUMS_REQUEST",
    GET_NEW_ALBUMS_SUCCESS: "GET_NEW_ALBUMS_SUCCESS",
    GET_FEATURED_ALBUMS_SUCCESS: "GET_FEATURED_ALBUMS_SUCCESS",
    GET_POPULAR_ALBUMS_SUCCESS: "GET_POPULAR_ALBUMS_SUCCESS",
    GET_RANDOM_ALBUMS_SUCCESS: "GET_RANDOM_ALBUMS_SUCCESS",
    GET_ALBUM_GRID_SUCCESS: "GET_ALBUM_GRID_SUCCESS",
    GET_ALBUMS_FAILURE: "GET_ALBUMS_FAILURE"
}