export const searchHistoryActionTypes = {
    GET_HISTORY: "GET_HISTORY",
    SET_HISTORY: "SET_HISTORY",
    ADD_TO_FAVORITE:"ADD_TO_FAVORITE",
    REMOVE_FROM_FAVORITE:"REMOVE_FROM_FAVORITE",
    REMOVE_ALL_UNFAVORITES:"REMOVE_ALL_UNFAVORITES"

}