export const wallpaperActionTypes = {
    GET_WALLPAPER_REQUEST: "GET_WALLPAPER_REQUEST",
    GET_WALLPAPER_SUCCESS: "GET_WALLPAPER_SUCCESS",
    GET_WALLPAPER_FAILURE: "GET_WALLPAPER_FAILURE",
    SEARCH_WALLPAPER_REQUEST: "SEARCH_WALLPAPER_REQUEST",
    SEARCH_WALLPAPER_SUCCESS: "SEARCH_WALLPAPER_SUCCESS",
    CLEAR_SEARCH: "CLEAR_SEARCH"

}