export const wallpaperActionTypes = {
    GET_WALLPAPER_REQUEST: "GET_WALLPAPER_REQUEST",
    GET_NEW_WALLPAPER_SUCCESS: "GET_NEW_WALLPAPER_SUCCESS",
    GET_FEATURED_WALLPAPER_SUCCESS: "GET_FEATURED_WALLPAPER_SUCCESS",
    GET_POPULAR_WALLPAPER_SUCCESS: "GET_POPULAR_WALLPAPER_SUCCESS",
    GET_RANDOM_WALLPAPER_SUCCESS: "GET_RANDOM_WALLPAPER_SUCCESS",
    GET_WALLPAPER_FAILURE: "GET_WALLPAPER_FAILURE",
    SEARCH_WALLPAPER_REQUEST: "SEARCH_WALLPAPER_REQUEST",
    SEARCH_WALLPAPER_SUCCESS: "SEARCH_WALLPAPER_SUCCESS",
    CLEAR_SEARCH: "CLEAR_SEARCH"

}